export interface PresignedUrlResponse {
  uploadUrl: string;
  publicUrl: string;
  key: string;
}

/**
 * Uploads a local file directly to AWS S3 using a secure presigned URL
 * generated by the Vercel serverless function (/api/presign).
 */
export async function uploadImageToS3(file: File): Promise<string> {
  // 1. Request presigned URL from Vercel Serverless Function
  const response = await fetch("/api/presign", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      filename: file.name,
      contentType: file.type || "image/jpeg",
    }),
  });

  if (!response.ok) {
    let errorMsg = "Error al solicitar URL firmada a S3";
    try {
      const errData = await response.json();
      if (errData.error) errorMsg = errData.error;
    } catch {
      // fallback
    }
    throw new Error(errorMsg);
  }

  const { uploadUrl, publicUrl } = (await response.json()) as PresignedUrlResponse;

  // 2. Direct PUT to S3 using the presigned URL
  const uploadResponse = await fetch(uploadUrl, {
    method: "PUT",
    headers: {
      "Content-Type": file.type || "image/jpeg",
    },
    body: file,
  });

  if (!uploadResponse.ok) {
    throw new Error(
      `Error al subir la imagen a S3 (${uploadResponse.status} ${uploadResponse.statusText}). Revisa los permisos de CORS del bucket.`
    );
  }

  // 3. Return the public URL for Firestore persistence
  return publicUrl;
}
